enable selecting test folder when using nbresult in notebooks
lewagon/nbresult pull request #6
Opened 2022-05-12 19:00 UTC by brunolajoie

The following PR updates nbresult (without breaking it)

## Before
Previously, we could only use nbresult in notebooks at the **root**
![image](https://user-images.githubusercontent.com/22095643/168147470-2440264e-cab6-4d21-a1b4-20e4d50ccdda.png)

## After
Now, we can specify in which `subdir` folder to store the `pickle` and where to read the `pickle` and the `test_xxx.py`
![image](https://user-images.githubusercontent.com/22095643/168147763-4242222f-7aa2-48d4-88f6-d8278cd102a0.png)

Demo repo as per screenshot [here](https://github.com/brunolajoie/nbresultdemo/) 

## Why need this ?
This can be useful for taxifare-model project, where we regroup all tests of the week in the `./tests` with 1 subdir per challenge, some test launched from notebooks in `./notebooks`, while some other are launched from `Makefile` and targetting python code located in `./taxifare_model/ml_logic` for instance

## Warning

One potential problem (**which is not the responsibility of nbresult I think**) is that using the makefile to run simply one command for all 3 tests will fail
```
pytest:
	PYTHONDONTWRITEBYTECODE=1 pytest -v --color=yes
```

Therefore, we could still upgrade nbresult and then split the make command

2022-05-12 19:01 UTC, brunolajoie commented
- What do you think about the unique Makefile command problem @gmanchon ?
- What do you think about the idea @krokrob ? (before diving into the code)

2022-05-12 19:20 UTC, krokrob commented
What does the `make` command returns (before diving into the code) ? cc @brunolajoie

2022-05-13 06:33 UTC, brunolajoie commented
Edit: actually, Make works!  Maybe I was too tired yesterday :) 
![image](https://user-images.githubusercontent.com/22095643/168224857-0a54af94-a59a-43fc-8487-89f49defd20c.png)

2022-05-13 06:34 UTC, brunolajoie commented
Actually, Make works as well! I was maybe too tired yesterday when I tried
![image](https://user-images.githubusercontent.com/22095643/168225092-f529ad09-8343-449d-8e5f-fe0d92260077.png)

2022-05-13 10:34 UTC, krokrob requested changes
Great improvement @brunolajoie , I have some suggestion

2022-05-13 10:34 UTC, krokrob commented on nbresult/__init__.py
> +from os.path import dirname, join, abspath
To be removed

2022-05-13 10:34 UTC, krokrob commented on nbresult/__init__.py
> +            tests_path = join(tests_path, self.subdir)
```suggestion
        while not os.path.isdir(os.path.join(cwd, 'tests')):
            cwd = os.path.dirname(cwd)
            if cwd == os.sep:
                raise NameError(
                    "Could not find /tests directory in any parent folder")

        tests_path = os.path.join(cwd, 'tests')

        if self.subdir is not None:
            tests_path = os.path.join(tests_path, self.subdir)
```

2022-05-13 10:34 UTC, krokrob commented on nbresult/__init__.py
> +        result_file = join(tests_path, f"{self.name}.pickle")
```suggestion
        result_file = os.path.join(tests_path, f"{self.name}.pickle")
```

2022-05-13 10:34 UTC, krokrob commented on nbresult/__init__.py
> +            abspath(join(cwd, '**', f'{name}.pickle')), recursive=True)[0]
```suggestion
        while not os.path.isdir(os.path.join(cwd, 'tests')):
            cwd = os.path.dirname(cwd)
            if cwd == os.sep:
                raise NameError(
                    "Could not find /tests directory in any parent folder")

        pickle_path = glob.glob(
            os.path.abspath(os.path.join(cwd, '**', f'{name}.pickle')), recursive=True)[0]
```

2022-05-16 11:59 UTC, brunolajoie commented on nbresult/__init__.py
> +from os.path import dirname, join, abspath
```suggestion
```

2022-05-16 12:01 UTC, brunolajoie commented
- comments fixed ✅ 
- tested again on nnresultdemo ✅ 

kev feel free to merge

2022-05-16 20:20 UTC, brunolajoie commented
@gmanchon let's merge?

2022-05-17 10:13 UTC, krokrob approved these changes

2022-05-17 10:29 UTC, krokrob commented
AWESOME @brunolajoie

2022-05-17 10:29 UTC, merged